# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
#parameters:
    #parameter_name: value

services:
    app.ads_provider.autoplius:
        class: AppBundle\AdsProvider\AutopliusAdsProvider
        arguments: ['@doctrine.orm.entity_manager']

    app.command.start_crawler:
        class: AppBundle\Command\StartCrawlerCommand
        tags:
          - { name: console.command }
        arguments:
          -
            - '@app.ads_provider.autoplius'
          - '@doctrine.orm.entity_manager'
